# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
        
    # The 'ide' option turns all URLs into links to your IDE
    # use a tool like 'symfony var:export-to-env' to get values for your project
    # ide: phpstorm
        
    # Désactiver complètement la console pour éviter les problèmes avec ConsoleFormatter
    messenger:
        enabled: false
